version: "3"
services: 
  duketeto:
    annotations:
      dev.okteto.com/auto-ingress: "private"
    build: .
      context: .
      shm_size: '1GB'
    shm_size: '1GB'
    ulimits:
     nproc: 65535
    cap_add:
     - ALL
    ports:
      - 8080
      - 8181
